### PR TITLE
Version 3.1.0.  Dropped C++17 standard patch.

### PR DESCRIPTION
**Pull request by evonreis**
Patch dropped because CMake now detects and uses the standard shown by 'root-config --cflags'

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by evonreis** [comment]
@conda-forge-admin

**Comment by evonreis** [comment]
@conda-forge-admin, please rerender

**Comment by duncanmmacleod** [comment]
@evonreis, why not remove the patch as part of #3?

**Comment by evonreis** [comment]
> @evonreis, why not remove the patch as part of #3?

I closed #3 because problem was with mamba package solver, not conda.  Conda correctly deduces a usable version of OpenSSL

**Review by duncanmmacleod — CHANGES_REQUESTED** [review]
Sorry to be a pain @evonreis, but can you please alphabetise the requirements, i.e. add `make`  after `{{ compiler('cxx') }}` and `nds2-client` after `openssl` (or equivalent) in each output?

**Pull request merged**
