### PR TITLE
Rebuild for root_base 6.30.4

### PR DESCRIPTION
**Pull request by rhyspoulton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rhyspoulton** [comment]
@conda-forge-admin, please rerender

**Comment by duncanmmacleod** [comment]
@rhyspoulton, did you manually edit the `.ci_support/*.yaml` files? If yes you don't want to do that. You want to copy the migration file from another feedstock, i.e: https://github.com/conda-forge/gwollum-feedstock/commit/59fedec605d5c83138820f3d6e784e7983234f78.

**Comment by rhyspoulton** [comment]
> @rhyspoulton, did you manually edit the `.ci_support/*.yaml` files? If yes you don't want to do that. You want to copy the migration file from another feedstock, i.e: [conda-forge/gwollum-feedstock@59fedec](https://github.com/conda-forge/gwollum-feedstock/commit/59fedec605d5c83138820f3d6e784e7983234f78).

Yes, I did. `.ci_support/migrations/root_base####.yaml` isn't currently present in this feedstock, so I thought I didn't need it. But I will add one now.

**Comment by rhyspoulton** [comment]
@conda-forge-admin, please rerender

**Comment by duncanmmacleod** [comment]
@rhyspoulton your commit e0adc70 should ideally add the migration file, and do nothing else, but it seems to have deleted a _lot_ of stuff. The conda smithy commit has recreated everything, I think, but next time I think you can make your commit as small as possible.

**Comment by rhyspoulton** [comment]
> @rhyspoulton your commit [e0adc70](https://github.com/conda-forge/cds-crtools-feedstock/commit/e0adc702632e88fbb34733ec869e986184d26044) should ideally add the migration file, and do nothing else, but it seems to have deleted a _lot_ of stuff. The conda smithy commit has recreated everything, I think, but next time I think you can make your commit as small as possible.

Ahh, that must have been caused by the failed rerender I tried to do locally but got killed.  It seems to have deleted them and automatically added them to my commit.

**Pull request closed without merging**
